name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
 
    env:
      DOCKER_IMAGE_NAME: my-html

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dockerhub login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME .

      - name: Tag and push docker image
        run: |
          docker tag $DOCKER_IMAGE_NAME:latest ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Docker Compose file to remote server
        run: scp docker-compose.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }}:/tmp


      - name: Connect to Remote Server and Deploy
        run: |
          # Replace 'your_username' and 'your_server_address' with your SSH username and server address
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }} 'cd /tmp && docker stack deploy -c docker-compose.yml myapp'
