name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: my-html

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dockerhub login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME .

      - name: Tag and push docker image
        run: |
          docker tag $DOCKER_IMAGE_NAME:latest ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest

      - name: Set up SSH and Deploy
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

      - name: Copy Docker Compose file to remote server
        run: scp -o StrictHostKeyChecking=no -o LogLevel=DEBUG docker-compose.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }} ~/deploy || true
        env:
          SSH_AUTH_SOCK: /tmp/ssh-ed25519/agent.1845
          SSH_AGENT_PID: 1846

      - name: Connect to Remote Server and Deploy
        run: |
          # Replace 'your_username' and 'your_server_address' with your SSH username and server address
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key
          ssh -v -i /tmp/private_key  ${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }} 'cd ~/deploy docker stack deploy -c docker-compose.yml myapp' 2>&1 | tee deployment_output.txt
