name: Pipeline ci/cd

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: my-html  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dockerhub login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME .

      - name: Tag and push docker image
        run: |
          docker tag $DOCKER_IMAGE_NAME:latest ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH keys
        run: |
             echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > /c/Users/oussa/.ssh/id_ed25519
             chmod 600 /c/Users/oussa/.ssh/id_ed25519



      - name: Deploy application to Docker Swarm
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }} "docker stack deploy --compose-file docker-compose.yml my_app"

