name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
 
    env:
      DOCKER_IMAGE_NAME: my-html

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dockerhub login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME .

      - name: Tag and push docker image
        run: |
          docker tag $DOCKER_IMAGE_NAME:latest ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"
          echo "SWARM_HOST: ${{ secrets.SWARM_MANAGER_IP }}"
          echo "SWARM_USERNAME: ${{ secrets.SSH_USERNAME }}"
          echo "SWARM_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Deploy to Docker Swarm
        uses: actions/checkout@v2
        with:
          host: ${{ secrets.SWARM_MANAGER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stack deploy --compose-file docker-compose.yml clppprog_clpppt0gftqg00adq050
