name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: my-html

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dockerhub login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build docker image
        run: docker build -t $DOCKER_IMAGE_NAME .

      - name: Tag and push docker image
        run: |
          docker tag $DOCKER_IMAGE_NAME:latest ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest

      - name: Set up SSH and Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key
        env:
          SSH_AUTH_SOCK: /tmp/ssh-agent.sock

      - name: Copy Docker Compose file to remote server
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/private_key docker-compose.yml "${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }}:/tmp" || true
          ssh -o StrictHostKeyChecking=no -i /tmp/private_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }} 'chmod +x /tmp/docker-compose.yml && ls -l /tmp && cat /tmp/docker-compose.yml' || true

      - name: Connect to Remote Server and Deploy
        run: |
          ssh -v -o StrictHostKeyChecking=no -i /tmp/private_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SWARM_MANAGER_IP }} 'docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && cd /tmp && docker stack deploy -c docker-compose.yml myapp' 2>&1 | tee deployment_output.txt
